import Head from 'next/head';
import Image from 'next/image';
import Link from 'next/link';
import { FaSearch } from 'react-icons/fa';
import Footer from '../components/Footer';
import HomeCard from '../components/HomeCard';
export default function Home() {
	return (
		<div className='scroll-smooth'>
			<Head>
				<title>Create Next App</title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/favicon.ico' />
				<link rel='stylesheet' href='https://rsms.me/inter/inter.css' />
			</Head>
			<div className='container mx-auto flex justify-between flex-wrap m-h-max py-5'>
				<h1>Hello</h1>

				<ul className='flex w-1/4 justify-between'>
					<li>
						<Link href='/'>Homes</Link>
					</li>
					<li>
						<Link href='/'>Friends</Link>
					</li>
					<li>
						<Link href='/'>Sign Up</Link>
					</li>
				</ul>
			</div>
			<div className='my-20'>
				<h3 className='text-center text-gray-400'>
					Shared apartments in Ireland
				</h3>
				<h1 className='text-center text-2xl font-medium mt-2'>
					Find your new Home in Ireland
				</h1>
				<div className='w-11/12 mx-auto'>
					<div className='flex w-1/3 mx-auto items-center justify-between h-12 bg-gray-100 rounded-full px-3 mt-4 relative'>
						<div className='flex items-center w-10/12'>
							<FaSearch color='#6B7280' />
							<input
								placeholder='Hello input'
								className='bg-gray-100 ml-1 focus:outline-none  w-10/12'
							/>
						</div>

						<div className='bg-slate-900 p-2 rounded-full w-20'>
							<p className='text-white text-center'>Search</p>
						</div>
					</div>
					<div>
						<div className='bg-red-100 overflow-hidden h-100 relative  rounded-2xl mt-20'>
							<Image
								src='https://images.pexels.com/photos/1396122/pexels-photo-1396122.jpeg'
								layout='fill'
								objectFit='cover'
								alt='hello'
							/>
						</div>
						<h3 className='mt-3 text-black'>Hello</h3>
						<h3 className='text-sm text-gray-400 my-1'>jhghf</h3>
						<h3 className='text-sm'>€850 per Month</h3>
						<section className='grid grid-cols-4 gap-6 mt-20'>
							<HomeCard />
							<HomeCard />
							<HomeCard />
							<HomeCard />
							<HomeCard />
							<HomeCard />
						</section>
						<div className='flex justify-center py-10'>
							<Link href='/home/hello'>
								<div className='bg-zinc-900 w-40 py-5 px-10 rounded-full'>
									<h1 className='text-white text-center'>View All</h1>
								</div>
							</Link>
						</div>
					</div>
				</div>
			</div>
			<Footer />
		</div>
	);
}
